---

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    post_install:
      - pip install poetry==1.3.2
      - cd cli && poetry config virtualenvs.create false
      - cd cli && poetry install --with doc

sphinx:
  configuration: docs/source/conf.py
