version: '3.1'
services:
  gw:
    build:
      context: .
    networks:
      - scw-sls-gw
    environment:
      SCW_ACCESS_KEY: '${SCW_ACCESS_KEY}'
      SCW_SECRET_KEY: '${SCW_SECRET_KEY}'
      S3_REGION: '${S3_REGION}'
      S3_ENDPOINT: '${S3_ENDPOINT}'
      S3_BUCKET_NAME: '${S3_BUCKET_NAME}'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
    ports:
      - 8080:8080
      - 8443:8443
      - 8001:8001
      - 8444:8444
    volumes:
      - ./:/app

  ping-checker:
    networks:
      - scw-sls-gw
    build:
      context: ./endpoints/ping/
    ports:
      - 8003:80

  func-a:
    networks:
      - scw-sls-gw
    build:
      context: ./endpoints/func-a/
    ports:
      - 8004:80

  func-b:
    networks:
      - scw-sls-gw
    build:
      context: ./endpoints/func-b/
    ports:
      - 8005:80

  minio:
    networks:
      - scw-sls-gw
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${SCW_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${SCW_SECRET_KEY}
    entrypoint: sh
    command: -c 'mkdir -p /data/${S3_BUCKET_NAME} && minio server /data --console-address ":9001"'

volumes:
  minio_storage: {}

networks:
 scw-sls-gw:
   driver: bridge
