version: '3.1'
services:
  gw:
    build:
      context: .
    networks:
      - scw-sls-gw
    environment:
      - SCW_ACCESS_KEY=some-key
      - SCW_S3_TOKEN=some-token
      - SCW_S3_BUCKET_NAME=some-bucket
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    ports:
      - 8080:8080
      - 8443:8443
      - 8001:8001
      - 8444:8444
    volumes:
      - ./:/app

  ping-checker:
    networks:
      - scw-sls-gw
    build:
      context: ./endpoints/ping/
    ports:
      - 8003:80

  func-a:
    networks:
      - scw-sls-gw
    build:
      context: ./endpoints/func-a/
    ports:
      - 8004:80

  func-b:
    networks:
      - scw-sls-gw
    build:
      context: ./endpoints/func-b/
    ports:
      - 8005:80

networks:
 scw-sls-gw:
   driver: bridge
