[tool.isort]
profile = "black"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
testpaths = ["tests"]

[tool.mypy]
exclude = ["venv", "endpoints"]
# TODO - enable mypy checking properly and fix issue with kong_pdk
ignore_missing_imports = true
