[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = [
  "--import-mode=importlib",
]

[tool.mypy]
exclude = ["venv", "endpoints"]
# TODO - enable mypy checking properly and fix issue with kong_pdk
ignore_missing_imports = true

