name: Set up SCW CLI
description: Install SCW CLI using repo secrets
runs:
  using: "composite"
  steps:
    - name: Install CLI and create config file
      uses: scaleway/action-scw@v0.0.1
      with:
        version: v2.14.0
        access-key: ${{ secrets.SCW_ACCESS_KEY }}
        secret-key: ${{ secrets.SCW_SECRET_KEY }}
        default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
        default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
        default-region: "fr-par"
        default-zone: "fr-par-1"
        save-config: true
