import os
import uuid
from typing import Generator

import pytest
from scaleway import Client
from scaleway.account import v2 as sdk

from tests.integration.environment import IntegrationEnvironment


@pytest.fixture(scope="session")
def integration_env() -> IntegrationEnvironment:
    if os.getenv("DEPLOY_ENV") == "scw":
        return IntegrationEnvironment.get_scw_env()
    return IntegrationEnvironment.get_docker_compose_env()


# Using scope="class" causes issue with teardown_class being called
# after attempting to delete the project, which causes it to fail
# because Cockpit is still activated.
@pytest.fixture(scope="module")
def tmp_scaleway_project() -> Generator[sdk.Project, None, None]:
    """Return a temporary Scaleway project."""
    client = Client.from_config_file_and_env()
    api = sdk.AccountV2API(client)
    project = None
    try:
        project = api.create_project(
            name=f"test-gateway-{uuid.uuid4()}",
            description="Generated by the Serverless Gateway integration tests",
        )
        yield project
    finally:
        if project:
            api.delete_project(project_id=project.id)
