name: Set up poetry
description: Install poetry and python dependencies
runs:
  using: "composite"
  steps:
    - uses: snok/install-poetry@v1
      with:
        version: 1.3.2
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cache poetry dependencies
      id: cache-gw-deps
      uses: actions/cache@v3
      with:
        path: .venv
        key: gw-pydeps-${{ hashFiles('**/poetry.lock') }}

    - name: Install poetry dependencies
      shell: bash
      working-directory: cli
      run: poetry install --no-interaction --no-root --with=dev
      if: steps.cache-gw-deps.outputs.cache-hit != 'true'
