name: build

on:
  push:
    tags:
      - 'v*.*.*'

env:
  TAG_BASE: scaleway/serverless-gateway

jobs:
  image-build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: "Get tag version"
        run: echo "TAG=$TAG_BASE:${GITHUB_REF#refs/tags/v*}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-poetry
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Push"
        uses: docker/build-push-action@v4
        with:
          push: true
          context: gateway
          tags: "${{ env.TAG }}"

  pypi-build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-poetry
      - name: "Set up PyPI auth"
        run: ./scripts/pypi_auth.sh ${{ secrets.PYPI_TOKEN }}
      - name: "Publish"
        run: ./scripts/publish.sh
