name: push to registry

on:
  push:
    branches: 
      - 'SRVLESS**'

env:
  TAG_BASE: scaleway/scw-sls-gw

jobs:
  image-build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
      - name: "Login to SCW registry"
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.SCW_REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_REGISTRY_KEY }}
      - name: "Get image tag"
        id: get_tag
        run: echo "tag=$TAG_BASE:$(cat VERSION)" >> $GITHUB_ENV
      - name: "Build"
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: "${{ env.tag }}"
      - name: "Push"
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "${{ env.tag }}"
        if: github.event_name != 'pull_request'