name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main,prod]
    types: [opened, synchronize, reopened, ready_for_review]

defaults:
  run:
    shell: bash

jobs:
  formatting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-poetry
      - run: make lint
        working-directory: cli
  unit-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-poetry
      - run: make test
        working-directory: cli
  int-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-cli
        with:
          access-key: "foo"
          secret-key: "00000000-0000-0000-0000-000000000000"
          project-id: "00000000-0000-0000-0000-000000000000"
          organization-id: "00000000-0000-0000-0000-000000000000"

      - uses: ./.github/actions/setup-poetry

      - name: Start the stack
        run: docker compose up -d
        working-directory: gateway

      - name: API gateway health check
        run: until curl http://localhost:8080/ping; do sleep 3; done

      - name: Set up local config
        run: poetry run scwgw local-config
        working-directory: cli

      - name: Run the tests
        run: poetry run pytest tests/integration
        working-directory: cli
