name: tests with deployed gateway

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test-deployed-gateway:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-poetry

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install npm dependencies
        run: npm install -g serverless serverless-scaleway-functions

      - name: Install scaleway CLI
        uses: ./.github/actions/setup-scaleway-cli
        with:
          scw-version: "2.13.0"
          scw-access-key: ${{ secrets.SCW_ACCESS_KEY }}
          scw-secret-key: ${{ secrets.SCW_SECRET_KEY }}
          scw-default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          scw-default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}

      - name: Deploy function fixtures
        working-directory: gateway/endpoints
        run: serverless deploy

      - name: Create Gateway namespace
        id: create-namespace
        run: |
          scwgw create-namespace
          scwgw await-namespace

      - name: Create Gateway container
        # We need to truncate gateway.env as it will override our env vars
        run: |
          scwgw create-containers
          scwgw await-containers

      - name: Run integration tests
        working-directory: cli
        run: |
          scwgw remote-config
          make test-int
        env:
          DEPLOY_ENV: "scw"

      - name: Delete Gateway namespace and container
        run: scwgw delete-namespace
        if: always()
